name: Deploy to Development

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build applications
      run: pnpm build
      env:
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

    - name: Authenticate to Google Cloud (Workload Identity)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        token_format: access_token
        audience: https://iam.googleapis.com/projects/998912996227/locations/global/workloadIdentityPools/github/providers/github

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Build and Deploy Cloud Run API
      run: |
        # Build the container image
        gcloud builds submit ./apps/api \
          --tag europe-west1-docker.pkg.dev/${{ secrets.FIREBASE_PROJECT_ID }}/cloud-run-source-deploy/collectr-api:latest
        
        # Deploy the built image to Cloud Run
        gcloud run deploy collectr-api \
          --image europe-west1-docker.pkg.dev/${{ secrets.FIREBASE_PROJECT_ID }}/cloud-run-source-deploy/collectr-api:latest \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID }}" \
          --set-env-vars="NODE_ENV=development"

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: |
        cd firebase
        firebase use dev
        firebase deploy --only firestore:rules,storage:rules,hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}